an = 2;
%     ./sum(vars.mb.mri.fs_vols,2),...
[rk(1,1) ,pk(1,1)] = partialcorr(sum(vars.mb.mri.fs_vols,2),... % tiv 
        anth(:,an),vars.mb.reg(:,1:2),...
        'rows','pairwise');

[rk(1,2) ,pk(1,2)] = partialcorr(sum(vars.mb.mri.fs_vols(:,[1:35 39:46 84:118 122:129]),2),... % gray matter only
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],...
        'rows','pairwise');
[rk(1,3) ,pk(1,3)] = partialcorr(sum(vars.mb.mri.fs_vols(:,[36 49:83 119 132:166]),2),... % white matter only
        anth(:,1),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],...
        'rows','pairwise');
    
[rk(1,4) ,pk(1,4)] = partialcorr(sum(vars.mb.mri.gy_area,2),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');
[rk(1,5) ,pk(1,5)] = partialcorr(mean(vars.mb.mri.gy_thick,2),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');
[rk(1,6) ,pk(1,6)] = partialcorr(sum(vars.mb.mri.gy_depth,2),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');

for i = 1:169
    [rm(i,1) ,pm(i,1)] = partialcorr(vars.mb.mri.fs_vols(:,i),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],...
        'rows','pairwise');
end

for ii = 1:62
    [rn(ii,1) ,pn(ii,1)] = partialcorr(vars.mb.mri.gy_area(:,ii),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');
    [rn(ii,2) ,pn(ii,2)] = partialcorr(vars.mb.mri.gy_thick(:,ii),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');
    [rn(ii,3) ,pn(ii,3)] = partialcorr(vars.mb.mri.gy_depth(:,ii),...
        anth(:,an),[vars.mb.reg(:,1:2) sum(vars.mb.mri.fs_vols,2)],'rows','pairwise');
end
    